[package]
name = "azure"
version = "0.4.1"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"

build = "build.rs"

[features]
default = []
plugins = ["serde", "serde_macros", "heapsize", "heapsize_plugin", "euclid/plugins"]


[dependencies]
euclid = "0.6.1"
heapsize = {version = ">=0.2, <0.4", optional = true}
heapsize_plugin = {version = "0.1.0", optional = true}
libc = "0.2"
serde = {version = "0.6.1", optional = true}
serde_macros = {version = "0.6.1", optional = true}
servo-skia = "=0.20130412.6"

[target.i686-unknown-linux-gnu.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }

[target.x86_64-unknown-linux-gnu.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }

[target.arm-unknown-linux-gnueabihf.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }
servo-egl = "0.2"

[target.aarch64-unknown-linux-gnu.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"
x11 = { version = "2.0.0", features = ["xlib"] }

[target.arm-linux-androideabi.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"
servo-egl = "0.2"

[target.x86_64-pc-windows-gnu.dependencies]
freetype = { git = "https://github.com/servo/rust-freetype" }
servo-freetype-sys = "2.4.11"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "0.2.0"
core-graphics = "0.2.0"
core-text = "1.0"
