[package]
name = "azure"
version = "0.2.1"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"

build = "build.rs"

[features]
default = []
plugins = ["serde", "serde_macros", "heapsize", "heapsize_plugin", "euclid/plugins"]



[dependencies]
libc = "*"
euclid = "0.3"
serde = {version = "*", optional = true}
serde_macros = {version = "*", optional = true}
heapsize = {version = "0.1.2", optional = true}
heapsize_plugin = {version = "0.1.0", optional = true}

[dependencies.skia]
git = "https://github.com/servo/skia"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.aarch64-unknown-linux-gnu.dependencies.x11]
version = "2.0.0"
features = ["xlib"]

[target.i686-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-linux-androideabi.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.aarch64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-pc-windows-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.i686-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-linux-androideabi.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.aarch64-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-pc-windows-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
core-graphics = "*"

[target.x86_64-apple-darwin.dependencies.core-text]
git = "https://github.com/servo/core-text-rs"

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"

[target.arm-unknown-linux-gnueabihf.dependencies.egl]
git = "https://github.com/servo/rust-egl"
