[package]
name = "azure"
version = "0.1.0"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"

build = "build.rs"

[dependencies]
libc = "*"
euclid = "0.1"

[dependencies.skia]
git = "https://github.com/servo/skia"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.i686-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-linux-androideabi.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.i686-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-linux-androideabi.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
core-graphics = "*"

[target.x86_64-apple-darwin.dependencies.core-text]
git = "https://github.com/servo/core-text-rs"

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"

[target.arm-unknown-linux-gnueabihf.dependencies.egl]
git = "https://github.com/servo/rust-egl"
