[package]
name = "azure"
version = "0.9.2"
authors = ["The Servo Project Developers"]
documentation = "http://doc.servo.org/azure/"

build = "build.rs"

[features]
default = []
plugins = ["serde", "serde_derive", "heapsize", "heapsize_derive"]

[build-dependencies]
cmake = "0.1"

[dependencies]
euclid = "0.10"
heapsize = {version = ">=0.2, <0.4", optional = true}
heapsize_derive = {version = "0.1.0", optional = true}
libc = "0.2"
serde = {version = "0.8", optional = true}
serde_derive = {version = "0.8", optional = true}
servo-skia = "0.20130412.24"

[target.'cfg(all(target_os = "linux", target_os = "android"))'.dependencies]
freetype = "0.1.3"
servo-freetype-sys = "4.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2.0.0", features = ["xlib"] }

[target.'cfg(target_os = "android")'.dependencies]
servo-egl = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.2.0"
core-graphics = "0.4"
core-text = "2.0"
